In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/ga_hits.csv')

In [3]:
df1 = pd.read_csv('data/ga_sessions.csv')

C:\Users\alexa\AppData\Local\Temp\ipykernel_24180\4203695756.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv('data/ga_sessions.csv')

In [11]:
df.describe()

           hit_time    hit_number  event_value
count  6.566148e+06  1.572647e+07          0.0
mean   2.091050e+05  2.356715e+01          NaN
std    4.032110e+05  2.887713e+01          NaN
min    0.000000e+00  1.000000e+00          NaN
25%    2.412000e+04  7.000000e+00          NaN
50%    8.994100e+04  1.500000e+01          NaN
75%    2.195352e+05  2.900000e+01          NaN
max    1.315688e+07  5.000000e+02          NaN

In [4]:
df.head(5)

,session_id,hit_date,hit_time,hit_number,hit_type,hit_referer,hit_page_path,event_category,event_action,event_label,event_value
0,5639623078712724064.1640254056.1640254056,2021-12-23,597864.0,30,event,NaN,sberauto.com/cars?utm_source_initial=google&ut...,quiz,quiz_show,NaN,NaN
1,7750352294969115059.1640271109.1640271109,2021-12-23,597331.0,41,event,NaN,sberauto.com/cars/fiat?city=1&city=18&rental_c...,quiz,quiz_show,NaN,NaN
2,885342191847998240.1640235807.1640235807,2021-12-23,796252.0,49,event,NaN,sberauto.com/cars/all/volkswagen/polo/e994838f...,quiz,quiz_show,NaN,NaN
3,142526202120934167.1640211014.1640211014,2021-12-23,934292.0,46,event,NaN,sberauto.com/cars?utm_source_initial=yandex&ut...,quiz,quiz_show,NaN,NaN
4,3450086108837475701.1640265078.1640265078,2021-12-23,768741.0,79,event,NaN,sberauto.com/cars/all/mercedes-benz/cla-klasse...,quiz,quiz_show,NaN,NaN

In [6]:
#Lest see the amount of unique values in each column
for column in df.columns:
    uniq = df[column].nunique()
    print(f"""Характеристика: {column}\nКоличество уникальных значений: {uniq}\nСписок значений:
    """)
    count = df[column].value_counts()
    print(count)
    print("\n")

Характеристика: session_id
Количество уникальных значений: 1734610
Список значений:

5442565791571325612.1632449195.1632449195    768
6568868914238486437.1632270313.1632270313    678
5959671972744778783.1632490527.1632490600    548
7452598043578978502.1632358598.1632358598    514
3070792010704358528.1629752408.1629752408    498
                                            ...
4570994095441102117.1630324006.1630324006      1
768506153535315810.1630314342.1630314342       1
5517253735248338264.1630315080.1630315080      1
4054272189286640867.1630334209.1630334209      1
5381267721977892188.1640271196.1640271196      1
Name: session_id, Length: 1734610, dtype: int64


Характеристика: hit_date
Количество уникальных значений: 226
Список значений:

2021-05-24    513035
2021-12-21    280192
2021-05-25    235805
2021-09-23    168899
2021-05-26    158382
               ...
2021-07-24     23490
2021-05-23     18773
2021-05-19     14605
2021-05-22     13917
2021-05-21     13497
Name: hit_date, Length: 226, dtype: int64


Характеристика: hit_time
Количество уникальных значений: 925887
Список значений:

0.0          41137
1.0          18522
2.0          10101
3.0           6060
4.0           4478
             ...
544067.0         1
698726.0         1
1200872.0        1
1484143.0        1
742820.0         1
Name: hit_time, Length: 925887, dtype: int64


Характеристика: hit_number
Количество уникальных значений: 500
Список значений:

3      1097355
4       928038
7       667634
8       572076
9       548347
        ...
479         43
497         43
462         41
494         41
486         41
Name: hit_number, Length: 500, dtype: int64


Характеристика: hit_type
Количество уникальных значений: 1
Список значений:

event    15726470
Name: hit_type, dtype: int64


Характеристика: hit_referer
Количество уникальных значений: 37873
Список значений:

HbolMJUevblAbkHClEQa    8879187
FwdMTcXzWAwhtsnMAbhS      91940
sAGDBCdeVPmQPwkVEcIX      53565
GQmOLxANuSeCxCanBpMl      35470
ZeRnFrHdnMmnqraghdGJ      23016
                         ...
VaOgrsicGpgIbzLNSDbc          1
rSeuBRLEcgyWsXrSYQqh          1
UNckxKWlzUxsKgvMBNdE          1
YZNVwxZKSbzYIwrGrgdY          1
tvGabHlPFDvTmIFiCKTL          1
Name: hit_referer, Length: 37873, dtype: int64


Характеристика: hit_page_path
Количество уникальных значений: 342715
Список значений:

podpiska.sberauto.com/                                                                                                                                                                                                  2793639
sberauto.com/cars?city=1&rental_page=rental_only&rental_car=rental_only&city=18                                                                                                                                         1103484
sberauto.com/cars?utm_source_initial=sbol&utm_medium_initial=banner&utm_campaign_initial=LEoPHuyFvzoNfnzGgfcd&utm_content_initial=vCIpmpaGBnIQhyYNkXqp&city=1&rental_page=rental_only&rental_car=rental_only&city=18     754215
sberauto.com/cars/f28947a1?rental_page=rental_car                                                                                                                                                                        264878
sberauto.com/cars/bf24b977?rental_page=rental_car                                                                                                                                                                        263966
                                                                                                                                                                                                                         ...
podpiska.sberauto.com/?fbclid=iwar09fvzokgiv3gx81ai3dyf2qcny_qa4zgby20oxibjfb0n-xjfftpexqbq                                                                                                                                   1
podpiska.sberauto.com/?fbclid=iwar05frzto9b6i3y-gkugl3rhizmjha7pznimzeix3tugv-6qdjdshjhwzrs                                                                                                                                   1
podpiska.sberauto.com/?yclid=4999432059093308360                                                                                                                                                                              1
podpiska.sberauto.com/?yclid=4994941468752008183                                                                                                                                                                              1
sberauto.com/moskva/cars?datefrom=2021&rental_car=rental_only&rental_page=rental_only&page=2                                                                                                                                  1
Name: hit_page_path, Length: 342715, dtype: int64


Характеристика: event_category
Количество уникальных значений: 52
Список значений:

card_web                         7456998
search_form                      2423605
sub_page_view                    1986074
sub_button_click                 1073471
listing_ads                      1040468
cars                              358915
sap_search_form                   356596
quiz                              263134
auth                              189373
sap_search__form                  188129
jivosite                           88443
chat                               85007
ad_banner                          40441
offers                             31218
navigation                         27075
footer                             20297
sub_submit                         18495
greenday_sub_button_click          15425
main_banners                       14142
profile_menu                       13879
scrolling_main_page                12160
active_invitation                   8478
header                              3531
my_idea                             2319
greenday_listing_ads                1792
main_services                       1464
phone                               1212
category_tile                        924
greenday_gtm.triggergroup            766
add_ad                               749
greenday_sub_submit                  732
credit_landing_pos                   274
add_ad_additional_information        122
main_advantages                      100
add_ad_vin                            88
pos_landing                           67
add_ad_publish_success                65
add_ad_options                        62
add_ad_city                           59
add_ad_photo                          55
add_ad_price                          53
add_ad_preview                        49
add_ad_description                    48
add_ad_documents                      46
credit_buttons                        27
wallet                                15
tesla                                 10
greenday_sub_page_view                 7
add_ad_form                            4
greenday_card_web                      4
app_banner                             2
titul_form                             1
Name: event_category, dtype: int64


Характеристика: event_action
Количество уникальных значений: 230
Список значений:

view_card                     3558985
view_new_card                 3551009
sub_landing                   1798117
go_to_car_card                 973666
sub_view_cars_click            791515
                               ...
click_on_android                    1
new_year_road_help_btn              1
titul_page_view                     1
show_pos_status_declined            1
survey_buy_after_sell_when          1
Name: event_action, Length: 230, dtype: int64


Характеристика: event_label
Количество уникальных значений: 39825
Список значений:

KclpemfoHstknWHFiLit    6505447
hAHqGICPFQiPwtzubOzs    1284914
OHfyUfDKdPgBdvelDlfG     626554
pzAKUYdRKNEUXxxBFUPX     358915
ghOrjqpgskpGHSFfBBsi     342500
                         ...
iFTveknOEiHmdgIHHqBZ          1
WKfoFxrMANSjHQMIhCZr          1
RAJXTkPWctNbMZubUIng          1
jRptuMMybqHerOxplPYo          1
aNlmojNIfsJaXKZHCDiU          1
Name: event_label, Length: 39825, dtype: int64


Характеристика: event_value
Количество уникальных значений: 0
Список значений:

Series([], Name: event_value, dtype: int64)